using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Autodesk.Revit.DB;
using KPLN_ModelChecker_Lib.LevelAndGridBoxUtil.Common;

namespace KPLN_ModelChecker_Lib.LevelAndGridBoxUtil
{
    /// <summary>
    /// –ö–ª–∞—Å—Å –¥–ª—è –≥–µ–Ω–µ—Ä–∞—Ü–∏–∏ —Å–æ–ª–∏–¥–∞ –º–µ–∂–¥—É —É—Ä–æ–≤–Ω–µ–º –∏ –æ–≥—Ä–∞–∂–¥–∞—é—â–∏–º–∏ —Å–µ–∫—Ü–∏—è–º–∏
    /// </summary>
    public class LevelAndGridSolid
    {
        /// <summary>
        /// –°–æ–ª–∏–¥ –≤ –≥—Ä–∞–Ω–∏—Ü–∞—Ö —É—Ä–æ–≤–Ω–µ–π –∏ –æ—Å–µ–π
        /// </summary>
        public Solid CurrentSolid { get; private set; }

        /// <summary>
        /// –°—Å—ã–ª–∫–∞ –Ω–∞ —Ç–µ–∫—É—â–∏–π CheckLevelOfInstanceLevelData
        /// </summary>
        public LevelData CurrentLevelData { get; private set; }

        /// <summary>
        /// –°—Å—ã–ª–∫–∞ –Ω–∞ CheckLevelOfInstanceGridData
        /// </summary>
        public GridData GridData { get; private set; }

        private LevelAndGridSolid(Solid solid, LevelData currentLevel, GridData gData)
        {
            CurrentSolid = solid;
            CurrentLevelData = currentLevel;
            GridData = gData;
        }

        /// <summary>
        /// –ü–æ–¥–≥–æ—Ç–æ–≤–∫–∞ –∫–æ–ª–ª–µ–∫—Ü–∏–∏ —Å–æ–ª–∏–¥–æ–≤ —Å –¥–∞–Ω–Ω—ã–º–∏ –ø–æ —Å–µ–∫—Ü–∏—è–º
        /// </summary>
        /// <param name="doc">Revit-–¥–æ–∫—É–º–µ–Ω—Ç</param>
        /// <param name="sectSeparParamName">–ü–∞—Ä–∞–º–µ—Ç—Ä –¥–ª—è —Ä–∞–∑–¥–µ–ª–µ–Ω–∏—è –æ—Å–µ–π –∏ —É—Ä–æ–≤–Ω–µ–π –ø–æ —Å–µ–∫—Ü–∏—è–º</param>
        /// <param name="levelIndexParamName">–ü–∞—Ä–∞–º–µ—Ç—Ä –¥–ª—è —Ä–∞–∑–¥–µ–ª–µ–Ω–∏—è —É—Ä–æ–≤–Ω–µ–π –ø–æ —ç—Ç–∞–∂–∞–º</param>
        /// <param name="floorScreedHeight">–¢–æ–ª—â–∏–Ω–∞ —Å—Ç—è–∂–∫–∏ –ø–æ–ª–∞ –ê–†</param>
        /// <param name="downAndTopExtra">–†–∞—Å—à–∏—Ä–µ–Ω–∏–µ –≥—Ä–∞–Ω–∏—Ü –¥–ª—è —Å–∞–º–æ–≥–æ –Ω–∏–∂–Ω–µ–≥–æ –∏ —Å–∞–º–æ–≥–æ –≤–µ—Ä—Ö–Ω–µ–≥–æ —É—Ä–æ–≤–Ω–µ–π</param>
        public static List<LevelAndGridSolid> PrepareSolids(Document doc, string sectSeparParamName,
            string levelIndexParamName, double floorScreedHeight = 0, double downAndTopExtra = 3)
        {
            List<LevelAndGridSolid> result = new List<LevelAndGridSolid>();

            List<GridData> gridDatas = GridData.GridPrepare(doc, sectSeparParamName);
            HashSet<string> multiGridsSet = new HashSet<string>(gridDatas.Select(g => g.CurrentSection));
            List<LevelData> levelDatas = multiGridsSet.Count == 1
                ? LevelData.LevelPrepare(doc, floorScreedHeight, downAndTopExtra, sectSeparParamName,
                    levelIndexParamName, multiGridsSet)
                : LevelData.LevelPrepare(doc, floorScreedHeight, downAndTopExtra, sectSeparParamName,
                    levelIndexParamName);

            // –ü–æ–¥–≥–æ—Ç–æ–≤–∫–∞ –ø—Ä–µ–¥–≤–∞—Ä–∏—Ç–µ–ª—å–Ω–æ–π –∫–æ–ª–ª–µ–∫—Ü–∏–∏ —ç–ª–µ–º–µ–Ω—Ç–æ–≤
            List<LevelAndGridSolid> preResult = new List<LevelAndGridSolid>();
            foreach (LevelData currentLevel in levelDatas)
            {
                foreach (GridData gData in gridDatas)
                {
                    if (currentLevel.CurrentSectionNumber.Equals(gData.CurrentSection))
                    {
                        Solid levSolid = CreateSolidInModel(currentLevel, gData);
                        LevelAndGridSolid secData = new LevelAndGridSolid(levSolid, currentLevel, gData);
                        preResult.Add(secData);
                    }
                }
            }

            // –û—á–∏—Å—Ç–∫–∞ –æ—Ç —Å–æ–ª–∏–¥–æ–≤, –¥–ª—è –≤—Å–ø–æ–º–æ–≥–∞—Ç–µ–ª—å–Ω—ã—Ö —É—Ä–æ–≤–Ω–µ–π –≤–Ω—É—Ç—Ä–∏ —Å–µ–∫—Ü–∏–π
            foreach (LevelAndGridSolid secData in preResult)
            {
                LevelAndGridSolid[] currentSectionAndAboveLevelsColl;
                if (secData.CurrentLevelData.CurrentAboveLevel != null)
                {
                    currentSectionAndAboveLevelsColl = preResult
                        .Where(r =>
                            r.GridData.CurrentSection.Equals(secData.GridData.CurrentSection)
                            && r.CurrentLevelData.CurrentAboveLevel != null
                            && r.CurrentLevelData.CurrentAboveLevel.Id == secData.CurrentLevelData.CurrentAboveLevel.Id)
                        .ToArray();
                }
                else
                {
                    currentSectionAndAboveLevelsColl = preResult
                        .Where(r =>
                            r.GridData.CurrentSection.Equals(secData.GridData.CurrentSection)
                            && r.CurrentLevelData.CurrentAboveLevel == null)
                        .ToArray();
                }

                if (currentSectionAndAboveLevelsColl.Count() == 1)
                    result.Add(secData);
                else if (currentSectionAndAboveLevelsColl.Any())
                {
                    LevelAndGridSolid minSecData = currentSectionAndAboveLevelsColl
                        .Aggregate((lvlMinElv, x) =>
                            (x.CurrentLevelData.CurrentLevel.Elevation <
                             lvlMinElv.CurrentLevelData.CurrentLevel.Elevation)
                                ? x
                                : lvlMinElv);
                    if (!result.Contains(minSecData))
                        result.Add(minSecData);
                }
                else
                {
                    result.Add(secData);
                }
            }

            // –ü—Ä–æ–≤–µ—Ä–∫–∞ –Ω–∞ –∫–æ–ª–ª–∏–∑–∏–∏ –º–µ–∂–¥—É Solid
            foreach (LevelAndGridSolid secData1 in result)
            {
                foreach (LevelAndGridSolid secData2 in result)
                {
                    // –î–ª—è –ø–∞—Ä–∫–∏–Ω–≥–∞ –¥–æ–ø—É—Å—Ç–∏–º—ã –ø–µ—Ä–µ—Å–µ—á–µ–Ω–∏—è —Å–æ–ª–∏–¥–æ–≤ —É—Ä–æ–≤–Ω–µ–π
                    if (
                        secData1.CurrentLevelData.CurrentSectionNumber.Equals(LevelData.ParLvlName)
                        || secData2.CurrentLevelData.CurrentSectionNumber.Equals(LevelData.ParLvlName)
                        || secData1.CurrentLevelData.CurrentSectionNumber.Equals(LevelData.StilLvlName)
                        || secData2.CurrentLevelData.CurrentSectionNumber.Equals(LevelData.StilLvlName)
                        ) 
                        continue;

                    if (secData1.Equals(secData2)) 
                        continue;
                    
                    Solid intersectionSolid = BooleanOperationsUtils
                        .ExecuteBooleanOperation(secData1.CurrentSolid,
                            secData2.CurrentSolid, BooleanOperationsType.Intersect);
                    if (intersectionSolid != null && intersectionSolid.Volume > 0)
                        throw new CheckerException(
                            "–°–æ–ª–∏–¥—ã —É—Ä–æ–≤–Ω–µ–π –ø–µ—Ä–µ—Å–µ–∫–∞—é—Ç—Å—è (–æ—à–∏–±–∫–∞ –≤ –∑–∞–ø–æ–ª–Ω–µ–Ω–∏–∏ –ø–∞—Ä–∞–º–µ—Ç—Ä–æ–≤ —Å–µ–ø–∞—Ä–∞—Ü–∏–∏ –æ–±—ä–µ–∫—Ç–∞, –ª–∏–±–æ —É—Ä–æ–≤–Ω–∏ –Ω–∞–∑–≤–∞–Ω—ã –Ω–µ –ø–æ BEP). " +
                            "–û—Ç–ø—Ä–∞–≤—å —Ä–∞–∑—Ä–∞–±–æ—Ç—á–∏–∫—É: " +
                            $"–£—Ä–æ–≤–Ω–∏ id: {secData1.CurrentLevelData.CurrentLevel.Id}, " +
                            $"{secData2.CurrentLevelData.CurrentLevel.Id} " +
                            $"–¥–ª—è —Å–µ–∫—Ü–∏–∏ ‚Ññ{secData1.GridData.CurrentSection} –∏ " +
                            $"–¥–ª—è —Å–µ–∫—Ü–∏–∏ ‚Ññ{secData2.GridData.CurrentSection}");
                }
            }

            return result;
        }

        /// <summary>
        /// –°–æ–∑–¥–∞–Ω–∏–µ Solid –ø–æ –ø–∞—Ä–∞–º–µ—Ç—Ä–∞–º
        /// </summary>
        /// <param name="levData">–î–∞–Ω–Ω—ã–µ –ø–æ —É—Ä–æ–≤–Ω—è–º</param>
        /// <param name="grData">–î–∞–Ω–Ω—ã–µ –ø–æ –æ—Å—è–º</param>
        /// <returns>–°–æ–∑–¥–∞–Ω–Ω–∞—è –ø–æ —Å–æ–ª–∏–¥—É –≥–µ–æ–º–µ—Ç—Ä–∏—è</returns>
        private static Solid CreateSolidInModel(LevelData levData, GridData grData)
        {
            List<XYZ> pointsOfGridsIntersect = GetPointsOfGridsIntersection(grData.CurrentGrids);
            pointsOfGridsIntersect.Sort(new PntComparer(GetCenterPointOfPoints(pointsOfGridsIntersect)));

            List<XYZ> pointsOfGridsIntersectDwn = new List<XYZ>();
            List<XYZ> pointsOfGridsIntersectUp = new List<XYZ>();
            foreach (XYZ point in pointsOfGridsIntersect)
            {
                XYZ newPointDwn = new XYZ(point.X, point.Y, levData.MinAndMaxLvlPnts[0]);
                pointsOfGridsIntersectDwn.Add(newPointDwn);
                XYZ newPointUp = new XYZ(point.X, point.Y, levData.MinAndMaxLvlPnts[1]);
                pointsOfGridsIntersectUp.Add(newPointUp);
            }

            List<Curve> curvesListDwn = GetCurvesListFromPoints(pointsOfGridsIntersectDwn);
            List<Curve> curvesListUp = GetCurvesListFromPoints(pointsOfGridsIntersectUp);
            CurveLoop curveLoopDwn = CurveLoop.Create(curvesListDwn);
            CurveLoop curveLoopUp = CurveLoop.Create(curvesListUp);
            try
            {
                CurveLoop[] curves = new CurveLoop[] { curveLoopDwn, curveLoopUp };
                SolidOptions solidOptions = new SolidOptions(ElementId.InvalidElementId, ElementId.InvalidElementId);
                return GeometryCreationUtilities.CreateLoftGeometry(curves, solidOptions);
            }
            catch (Autodesk.Revit.Exceptions.InvalidOperationException)
            {
                StringBuilder sb = new StringBuilder();
                foreach (Grid gr in grData.CurrentGrids)
                {
                    sb.Append(gr.Id);
                    sb.Append(", ");
                }

                throw new CheckerException(
                    "–ü–æ–≥—Ä–∞–Ω–∏—á–Ω—ã–µ –æ—Å–∏ –æ–±—è–∑–∞—Ç–µ–ª—å–Ω–æ –¥–æ–ª–∂–Ω—ã –ø–µ—Ä–µ—Å–µ–∫–∞—Ç—å—Å—è! –ü—Ä–æ–≤–µ—Ä—å –æ—Å–∏ id: " +
                    $"{sb.ToString().TrimEnd(", ".ToArray())}");
            }
        }

        /// <summary>
        /// –¢–æ—á–∫–∏ –ø–µ—Ä–µ—Å–µ—á–µ–Ω–∏—è –æ—Å–µ–π
        /// </summary>
        /// <param name="grids">–°–ø–∏—Å–æ–∫ –æ—Å–µ–π</param>
        private static List<XYZ> GetPointsOfGridsIntersection(HashSet<Grid> grids)
        {
            List<XYZ> pointsOfGridsIntersect = new List<XYZ>();
            foreach (Grid grid1 in grids)
            {
                if (grid1 == null) 
                    continue;
                
                Curve curve1 = grid1.Curve;
                foreach (Grid grid2 in grids)
                {
                    if (grid2 == null) 
                        continue;
                    
                    if (grid1.Id == grid2.Id) 
                        continue;
                    
                    Curve curve2 = grid2.Curve;
                    curve1.Intersect(curve2, out IntersectionResultArray intersectionResultArray);

                    // –õ–∏–Ω–∏–∏ –Ω–µ –ø–µ—Ä–µ—Å–µ–∫–∞—é—Ç—Å—è. –ù—É–∂–Ω–æ –ø—Ä–æ–≤–µ—Ä–∏—Ç—å –≤–µ–∫—Ç–æ—Ä–∞–º–∏
                    if (intersectionResultArray == null || intersectionResultArray.IsEmpty)
                    {
                        XYZ vectorIntersection = GetVectorsIntersectPnt(
                            curve1.GetEndPoint(0), 
                            curve1.GetEndPoint(1), 
                            curve2.GetEndPoint(0), 
                            curve2.GetEndPoint(1));

                        if (vectorIntersection != null
                            && !pointsOfGridsIntersect.Any(pgi => vectorIntersection.IsAlmostEqualTo(pgi)))
                        {
                            pointsOfGridsIntersect.Add(vectorIntersection);
                        }
                    }
                    // –õ–∏–Ω–∏–∏ –ø–µ—Ä–µ—Å–µ–∫–∞—é—Ç—Å—è, –ø–æ–ª—É—á–∞–µ–º —Ä–µ–∑—É–ª—å—Ç–∞—Ç
                    else
                    {
                        foreach (IntersectionResult intersection in intersectionResultArray)
                        {
                            XYZ point = intersection.XYZPoint;
                            if (!pointsOfGridsIntersect.Any(pgi => point.IsAlmostEqualTo(pgi)))
                                pointsOfGridsIntersect.Add(point);
                        }
                    }
                }
            }
            
            return pointsOfGridsIntersect;
        }

        private static XYZ GetVectorsIntersectPnt(XYZ startPoint1, XYZ endPoint1, XYZ startPoint2, XYZ endPoint2)
        {
            XYZ direction1 = endPoint1 - startPoint1;
            XYZ direction2 = endPoint2 - startPoint2;

            // –ü—Ä–æ–≤–µ—Ä—è–µ–º –Ω–∞ –ø–∞—Ä–∞–ª–ª–µ–ª—å–Ω–æ—Å—Ç—å (–µ—Å–ª–∏ –≤–µ–∫—Ç–æ—Ä–Ω–æ–µ –ø—Ä–æ–∏–∑–≤–µ–¥–µ–Ω–∏–µ = 0, —Ç–æ –ª–∏–Ω–∏–∏ –ø–∞—Ä–∞–ª–ª–µ–ª—å–Ω—ã)
            XYZ crossProduct = direction1.CrossProduct(direction2);
            
            // –õ–∏–Ω–∏–∏ –ø–∞—Ä–∞–ª–ª–µ–ª—å–Ω—ã –∏ –Ω–µ –ø–µ—Ä–µ—Å–µ–∫–∞—é—Ç—Å—è
            if (crossProduct.IsZeroLength())
                return null;
            // –õ–∏–Ω–∏–∏ –Ω–µ –ø–∞—Ä–∞–ª–ª–µ–ª—å–Ω—ã, –ø—Ä–æ–≤–µ—Ä–∏–º –∏—Ö –Ω–∞ –ø–µ—Ä–µ—Å–µ—á–µ–Ω–∏–µ
            else
            {
                // –†–∞—Å—Å—á–∏—Ç—ã–≤–∞–µ–º –ø–∞—Ä–∞–º–µ—Ç—Ä t1 –¥–ª—è –ø–µ—Ä–µ—Å–µ—á–µ–Ω–∏—è –ø–µ—Ä–≤–æ–π –ª–∏–Ω–∏–∏ —Å –ø—Ä–æ–¥–æ–ª–∂–µ–Ω–∏–µ–º –≤—Ç–æ—Ä–æ–π –ª–∏–Ω–∏–∏
                double t1 = ((startPoint2 - startPoint1).CrossProduct(direction2)).DotProduct(crossProduct) 
                            / crossProduct.DotProduct(crossProduct);

                // –†–∞—Å—Å—á–∏—Ç—ã–≤–∞–µ–º –ø–∞—Ä–∞–º–µ—Ç—Ä t2 –¥–ª—è –ø–µ—Ä–µ—Å–µ—á–µ–Ω–∏—è –≤—Ç–æ—Ä–æ–π –ª–∏–Ω–∏–∏ —Å –ø—Ä–æ–¥–æ–ª–∂–µ–Ω–∏–µ–º –ø–µ—Ä–≤–æ–π –ª–∏–Ω–∏–∏
                double t2 = ((startPoint2 - startPoint1).CrossProduct(direction1)).DotProduct(crossProduct) 
                            / crossProduct.DotProduct(crossProduct);

                // –ê–Ω–∞–ª–∏–∑ —Ç–æ—á–∫–∏ –ø–µ—Ä–µ—Å–µ—á–µ–Ω–∏—è –Ω–∞ –∏–∑–±—ã—Ç–æ—á–Ω—É—é —É–¥–∞–ª–µ–Ω–Ω–æ—Å—Ç—å (–Ω–∞–ø—Ä–∏–º–µ—Ä, —É–¥–∞–ª–µ–Ω–æ –±–æ–ª—å—à–µ —á–µ–º –Ω–∞ 30 –º)
                XYZ tempIntersectionPnt = startPoint1 + t1 * direction1;
                double distance = Math.Abs(startPoint1.DistanceTo(tempIntersectionPnt)) - Math.Abs(startPoint1.DistanceTo(endPoint1));
                if (Math.Abs(distance) > 100 )
                    return null;

                // ùë°2 –¥–∞—ë—Ç —Ç–æ—á–∫—É –ø–µ—Ä–µ—Å–µ—á–µ–Ω–∏—è –Ω–∞ –≤—Ç–æ—Ä–æ–π –ª–∏–Ω–∏–∏, –Ω–æ –≤ –Ω–∞—à–µ–º —Å–ª—É—á–∞–µ –¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å —Ç–æ–ª—å–∫–æ t1, —á—Ç–æ–±—ã –ø–æ–ª—É—á–∏—Ç—å —Ç—É –∂–µ —Å–∞–º—É—é —Ç–æ—á–∫—É –ø–µ—Ä–µ—Å–µ—á–µ–Ω–∏—è –≤ –º–∏—Ä–æ–≤—ã—Ö –∫–æ–æ—Ä–¥–∏–Ω–∞—Ç–∞—Ö.
                // –¢–æ –µ—Å—Ç—å –æ–¥–Ω–æ–π —Ç–æ—á–∫–∏ –ø–µ—Ä–µ—Å–µ—á–µ–Ω–∏—è –¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ, –∏ –º—ã –º–æ–∂–µ–º –≤—ã–±—Ä–∞—Ç—å –ª—é–±—É—é –∏–∑ –¥–≤—É—Ö –ª–∏–Ω–∏–π –¥–ª—è –µ—ë –≤—ã—á–∏—Å–ª–µ–Ω–∏—è.
                return startPoint1 + t1 * direction1;
            }
        }

        /// <summary>
        /// –¶–µ–Ω—Ç—Ä –º–µ–∂–¥—É —Ç–æ—á–∫–∞–º–∏
        /// </summary>
        /// <param name="pointsOfGridsIntersect">–°–ø–∏—Å–æ–∫ —Ç–æ—á–µ–∫</param>
        private static XYZ GetCenterPointOfPoints(List<XYZ> pointsOfGridsIntersect)
        {
            double totalX = 0, totalY = 0, totalZ = 0;
            
            foreach (XYZ xyz in pointsOfGridsIntersect)
            {
                totalX += xyz.X;
                totalY += xyz.Y;
                totalZ += xyz.Z;
            }
            
            double centerX = totalX / pointsOfGridsIntersect.Count;
            double centerY = totalY / pointsOfGridsIntersect.Count;
            double centerZ = totalZ / pointsOfGridsIntersect.Count;

            return new XYZ(centerX, centerY, centerZ);
        }

        private static List<Curve> GetCurvesListFromPoints(List<XYZ> pointsOfGridsIntersect)
        {
            List<Curve> curvesList = new List<Curve>();
            for (int i = 0; i < pointsOfGridsIntersect.Count; i++)
            {
                if (i == pointsOfGridsIntersect.Count - 1)
                {
                    curvesList.Add(Line.CreateBound(pointsOfGridsIntersect[i], pointsOfGridsIntersect[0]));
                    continue;
                }
                curvesList.Add(Line.CreateBound(pointsOfGridsIntersect[i], pointsOfGridsIntersect[i + 1]));

            }
            return curvesList;
        }
    }
}
